"""houses

Revision ID: 217cebdf8a0b
Revises: feb2d93fb123
Create Date: 2020-12-26 20:13:49.273361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '217cebdf8a0b'
down_revision = 'feb2d93fb123'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('houses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=140), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_houses_name'), 'houses', ['name'], unique=True)
    op.create_table('user_houses',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('house_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['house_id'], ['houses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_houses')
    op.drop_index(op.f('ix_houses_name'), table_name='houses')
    op.drop_table('houses')
    # ### end Alembic commands ###
