"""empty message

Revision ID: 7327e21117bd
Revises: 89ed69c900aa
Create Date: 2021-01-03 17:40:02.579070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7327e21117bd'
down_revision = '89ed69c900aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_houses', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_houses', 'created_at')
    # ### end Alembic commands ###
