"""users created_at

Revision ID: b84db7d74d75
Revises: 644ab50bb5cf
Create Date: 2020-12-17 23:09:28.581214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b84db7d74d75'
down_revision = '644ab50bb5cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flat_mate', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flat_mate', 'created_at')
    # ### end Alembic commands ###
